title: Vegan hackathon
email: krisztian.toth@maveg.hu
description: >- # this means to ignore newlines until "baseurl:"
  Vegan hackathon in Budapest.
baseurl: "/hackathon" # the subpath of your site, e.g. /blog
url: "https://selator.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: selator
github_username:  selator

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

include: ['_projects']
